import MainHeader from "@/components/Header/MainHeader";
import "./globals.css";
import "./index.css";
import Footer from "@/components/footer/Footer";




export const metadata = {
  title: "Traveling to the future",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainHeader />
        <section className="container">{children}</section>

        <Footer />
      </body>
    </html>
  );
}
